name: CI
on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
 
  deploy:
   
    runs-on: ubuntu-latest

    steps:
        - name: Run a one-line script
          run: echo Hello, world!

        - name: Deploy to Server 1
          uses: appleboy/ssh-action@master

          with:
           KEY: ${{ secrets.EC2_SSH_KEY }}
           HOST: ${{ secrets.HOST_DNS }}
           USERNAME: ${{ secrets.USERNAME }}
           TARGET: ${{ secrets.TARGET_DIR }}
           script: |
             cd /home/ubuntu/test/test_repo
             git pull origin main

    #  - uses: actions/checkout@v2


             
             
             
             
             
             
             #git clone git@github.com:MahnoorShafique/test_repo.git
             # git pull origin main
            # echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
           # ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
        # env:
        #   SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
        #   REMOTE_HOST: ${{secrets.HOST_DNS}}
        #   REMOTE_USER: ${{secrets.USERNAME}}
        #   TARGET: ${{secrets.TARGET_DIR}}
