name: CI
on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
 
  deploy:
   
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      
      - name: Run a one-line script
        run: echo Hello, world!
     
      - name: Deploy to Server 1
        uses: appleboy/ssh-action@master

        env:
           SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
           REMOTE_HOST: ${{ secrets.HOST_DNS }}
           REMOTE_USER: ${{ secrets.USERNAME }}
           TARGET: ${{ secrets.TARGET_DIR }}
        # env:
        #   SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
        #   REMOTE_HOST: ${{secrets.HOST_DNS}}
        #   REMOTE_USER: ${{secrets.USERNAME}}
        #   TARGET: ${{secrets.TARGET_DIR}}
